// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMo0HGa-3JQifKsQiPUW_dQoZnRyhAZFg',
    appId: '1:348801498106:web:8b102da9d967d8ce788243',
    messagingSenderId: '348801498106',
    projectId: 'hnpna-3e37e',
    authDomain: 'hnpna-3e37e.firebaseapp.com',
    storageBucket: 'hnpna-3e37e.appspot.com',
    measurementId: 'G-2YR39W8XT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy9fDDBes1bKZ8XpK3bM6AwAqd2TmMmvA',
    appId: '1:348801498106:android:7c678d94cbd82456788243',
    messagingSenderId: '348801498106',
    projectId: 'hnpna-3e37e',
    storageBucket: 'hnpna-3e37e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwItoRuAeATXuEqLWkCLElS2n7lFr9nw',
    appId: '1:348801498106:ios:85dd1f7de4bd401a788243',
    messagingSenderId: '348801498106',
    projectId: 'hnpna-3e37e',
    storageBucket: 'hnpna-3e37e.appspot.com',
    iosBundleId: 'com.example.hnpna0621',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwItoRuAeATXuEqLWkCLElS2n7lFr9nw',
    appId: '1:348801498106:ios:85dd1f7de4bd401a788243',
    messagingSenderId: '348801498106',
    projectId: 'hnpna-3e37e',
    storageBucket: 'hnpna-3e37e.appspot.com',
    iosBundleId: 'com.example.hnpna0621',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMo0HGa-3JQifKsQiPUW_dQoZnRyhAZFg',
    appId: '1:348801498106:web:758c7d8ce14fa9ef788243',
    messagingSenderId: '348801498106',
    projectId: 'hnpna-3e37e',
    authDomain: 'hnpna-3e37e.firebaseapp.com',
    storageBucket: 'hnpna-3e37e.appspot.com',
    measurementId: 'G-7VEED0S9C2',
  );
}
